[versions]
kotlin = "2.3.0-RC"
paper = "1.21.4-R0.1-SNAPSHOT"
velocity = "3.4.0-SNAPSHOT"
shadow = "9.2.2"
run-paper = "3.0.2"
resource-factory = "1.3.1"
kotlinx-serialization = "1.6.3"
chzzk = "0.0.8"
exposed = "0.57.0"
essentialsx = "2.21.2"
placeholderapi = "2.11.6"
mockk = "1.13.9"
junit = "6.0.1"
ktlint = "14.0.1"

[libraries]
# Paper API
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

# Velocity API
velocity-api = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }

# Kotlin
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# ChzzkMultipleUser
chzzk-core = { group = "io.papermc.chzzkmultipleuser", name = "core", version.ref = "chzzk" }
chzzk-common = { group = "io.papermc.chzzkmultipleuser", name = "common", version.ref = "chzzk" }
chzzk-database = { group = "io.papermc.chzzkmultipleuser", name = "database", version.ref = "chzzk" }
chzzk-feature-integration = { group = "io.papermc.chzzkmultipleuser", name = "feature-integration", version.ref = "chzzk" }
chzzk-messaging = { group = "io.papermc.chzzkmultipleuser", name = "messaging", version.ref = "chzzk" }

# Exposed
exposed-core = { group = "org.jetbrains.exposed", name = "exposed-core", version.ref = "exposed" }
exposed-dao = { group = "org.jetbrains.exposed", name = "exposed-dao", version.ref = "exposed" }

# Optional dependencies
essentialsx = { group = "net.essentialsx", name = "EssentialsX", version.ref = "essentialsx" }
placeholderapi = { group = "me.clip", name = "placeholderapi", version.ref = "placeholderapi" }

# Test dependencies
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
resource-factory = { id = "xyz.jpenilla.resource-factory-bukkit-convention", version.ref = "resource-factory" }
resource-factory-velocity = { id = "xyz.jpenilla.resource-factory-velocity-convention", version.ref = "resource-factory" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
